name: Local Docker CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t currency-ci-cd:latest .

      - name: Run container
        run: |
          docker run -d --name currency_container -p 3000:3000 currency-ci-cd:latest
          echo "Waiting for app to start..."
          for i in {1..10}; do
            if curl -s http://localhost:3000/health | grep -q "ok"; then
              echo "App is up!"
              break
            fi
            echo "Waiting ($i)..."
            sleep 2
          done

      - name: Run tests
        run: node app/test.js

      - name: Stop and remove container
        if: always()
        run: |
          docker stop currency_container || true
          docker rm currency_container || true